### ISSUE TITLE
Sorted by Name, Sorted by Usage

### ISSUE THREAD

**Issue by pronouncedJerry** [dominictarr/your-web-app-is-bloated#10]
Quickly put this together during my lunch:
https://docs.google.com/spreadsheets/d/1RYRBUifaDXdCawm86lCKmNQAh0nDlwnElFVxVsydC7M/edit?usp=sharing

app | usage (mib)
google inbox | 215
gmail (standard) | 158
google sheets (spreadsheet) | 96.98
slack | 76.53
google-maps | 65.61
youtube video | 59.04
facebook newsfeed | 56.12
nytimes | 56.08
riot | 55.31
toggle | 49.77
google docs (document) | 46.57
soundcloud (track open) | 45.8
hackmd (document) | 44.9
reddit | 43.77
tweetdeck | 40.38
jitsi | 40.21
the onion | 38.3
rocketchat | 32.12
open collective | 31.22
youtube | 30
sandstorm (spreadsheet) | 27.63
pinterest | 26.8
images.google (result) | 26.41
twitter | 25.09
google docs | 24.7
facebook | 23.49
soundcloud | 22
medium | 18.53
medium (article) | 17.99
bandcamp | 14.86
google results | 14.77
google | 11.3
google hangouts | 10.76
talky | 9.4
bandcamp (album page) | 8.76
github | 7.41
the guardian | 7.36
duckduckgo images (result) | 7.31
openstreetmap (on new york, transportation layer) | 6.72
wikipedia page | 5.93
duckduckgo | 5.63
duckduckgo results | 4.81
meatspace chat | 4.48
stackoverflow | 2.55
wikipedia | 1.73
gmail (vintage) | 0.81

**Comment by dominictarr** [comment]
it's now sorted

**Comment by pronouncedJerry** [comment]
looks awesome!
