### ISSUE TITLE
Response

### ISSUE THREAD

**Issue by dark-swordsman** [dominictarr/your-web-app-is-bloated#12]
I figured I would write out a response on your article.

1) Memory usage on a video to be higher is expected and it isn't fair to say it's bloated because of it. Since YouTube usually downscales videos to a lower bitrate of about 3,000 Kbps, you can expect about 30-40 MB of ram usage if it buffers 10 seconds of it at a time (and more if it buffers the whole video over time).

2) I'm not sure what's up with Gmail, but if you open up the elements tab, you see that that HTML document, after it's done being computed, is gigantic. From an eye glance, it seems that about 50% of it is CSS and 20% of it is JavaScript. Much of it is unneeded and repetitive. I can agree with you there that Gmail seems to be bloated for no reason.

Also to mention, it seems that they have an invisible "Oauth" iFrame at the bottom that seems to take up about 10% of the document. 

3) I'm glad that you wrote this to bring to light that web-app developers may want to take a closer look at memory usage, but I think you could've gone a little deeper.

I would first consider what the web app is doing. Something like YouTube makes sense for memory usage since it has large videos. Facebook can make sense since they show you so many different things on a page, as well as running a lot of data collection scripts and other things.

It's a more complicated issue than what you have posted (with misspellings and all). 

Javascript garbage collects itself, so generally, there isn't a need to look at garbage collection in the first place. The only exception would be if you are referencing objects that end up in an open state. What I mean by this is objects that are part of another object that is actively used, like something polling mouse cursor location and what not, but that usually doesn't happen.

**Comment by dominictarr** [comment]
I didn't call youtube bloated. 60mb for youtube seemed reasonable... but if can build youtube in 60 it really doesn't seem reasonable that something like fb needs that much!

btw, I just checked: vimeo can play a video using only 30mb! (I'll update the report later)

garbage collection doesn't mean you don't need to think about memory. GC will remove what you are not using, but if you have a design that uses a lot of memory, it's not gonna help!

**Comment by dark-swordsman** [comment]
My bad, I referenced the YouTube part wrong.

As far as garbage collection, what I meant was that, since many that learn JavaScript aren't exposed to the same things as C or Java where you do need to worry about memory stuff, people, I think, generally forget about it. 

It surely should be something people look at, and I look at it myself.
