### ISSUE TITLE
Add mobile versions of sites for comparison

### ISSUE THREAD

**Issue by Thrilleratplay** [dominictarr/your-web-app-is-bloated#14]
It would be interesting to see how the mobile sites, where size really matters, stack up.

Another interesting size comparison would be using [Links](http://links.twibright.com) or [Browsh](https://www.brow.sh)

**Comment by dominictarr** [comment]
I added mobile versions, of google apps, fb, and twitter. Interestingly google's mobile apps are really good. looks like the others just restyle their desktop app though.
