### ISSUE TITLE
Hypothesis on memory

### ISSUE THREAD

**Issue by WizardOfAus** [dominictarr/your-web-app-is-bloated#4]
Why do you think Google's uses that much memory for a static web page?

**Comment by dominictarr** [comment]
too much javascript! probably it's stuff for search suggestions. Also, user tracking.
large corporations such as google are usually very adverse to breaking anything, so they add stuff and don't remove it, and over time it accumulates.

**Comment by WizardOfAus** [comment]
I had not thought of that (breaking stuff, not removing), interesting observation thank you!
